language: scala

install:
  - curl -L https://github.com/lihaoyi/mill/releases/download/0.5.1/0.5.1 > mill && chmod +x mill

script:
  - ./mill __.compile
  - ./mill __.test

deploy:
  skip_cleanup: true
  provider: script
  script: ci/deploy.sh
  on:
    tags: true

cache:
  directories:
    - $HOME/.coursier
    - $HOME/.mill/download
